### ISSUE TITLE
about test dataset

### ISSUE THREAD

**Issue by masashi2ueda** [QuindiTech/VAE_ISIC2018#2]
In your provided test dataset, there are 350 NV images(NV_outlier\vae_test\NV). But in validation dataset, there are  only 336 NV images(NV_outlier\vae_train\val\normal). Where are 23 images from? Actually in your paper, it is written that "we select 250 images from the validation". Thank you.

**Comment by JACKHAHA363** [comment]
Thanks for your interest in our work! I re-download data on the link on website, and here is the number reported.
```
╭─yuchen@yuchen ~/QuindiTech/VAE_ISIC2018/NV_outlier/vae_test  ‹nv_exp*› 
╰─➤  ls NV | wc -l
350
╭─yuchen@yuchen ~/QuindiTech/VAE_ISIC2018/NV_outlier/vae_test  ‹nv_exp*› 
╰─➤  ls AKIEC | wc -l
100
╭─yuchen@yuchen ~/QuindiTech/VAE_ISIC2018/NV_outlier/vae_test  ‹nv_exp*› 
╰─➤  ls BCC | wc -l  
100
╭─yuchen@yuchen ~/QuindiTech/VAE_ISIC2018/NV_outlier/vae_test  ‹nv_exp*› 
╰─➤  ls BKL | wc -l
100
╭─yuchen@yuchen ~/QuindiTech/VAE_ISIC2018/NV_outlier/vae_test  ‹nv_exp*› 
╰─➤  ls DF | wc -l 
100
╭─yuchen@yuchen ~/QuindiTech/VAE_ISIC2018/NV_outlier/vae_test  ‹nv_exp*› 
╰─➤  ls MEL | wc -l
100
╭─yuchen@yuchen ~/QuindiTech/VAE_ISIC2018/NV_outlier/vae_test  ‹nv_exp*› 
╰─➤  ls VASC | wc -l
100
```
There is a bug in our data generating code. We select 250 images from the validation, and we again select 100 NV images from all NV images and add into the test. We are sorry for this major mistake. We would re-run the experiment and update the result.

**Comment by masashi2ueda** [comment]
Thank you for answering my question. I look forward to your updates.
